### ISSUE TITLE
($date) must be of type ?DateTime, bool given

### ISSUE THREAD

**Issue by RyanBlundell** [Moskito89/php-moon-phase#40]
Hi there,

The past version allowed us to set custom dates/times by using a format such as 

https://github.com/Moskito89/php-moon-phase/issues/28
`$moon = new Solaris\MoonPhase(strtotime(date('Y-m-d H:i')));`

However after upgrading I get the following error

Uncaught exception 'TypeError' with message 'Solaris\MoonPhase::__construct(): Argument #1 ($date) must be of type ?DateTime, bool given

Cheers

**Comment by Moskito89** [comment]
Hello @RyanBlundell,

thanks for the feedback, the constructor has indeed changed in `v2.0` (and unfortunately was not documented).

If your call was so far:

```
$date = date('Y-m-d H:i:s');
$time = strtotime($date);
$moonPhase = new MoonPhase($time);
```

it must be like this now:

```
$dateTime = new DateTime('now');
$moonPhase = new MoonPhase($dateTime);
```

Regardless, I'm wondering about your error message, because it talks about you (accidentally) passing a boolean, but `strtotime` should return an integer. Maybe you have another problem here.

I will update the documentation in the next days.
